services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.36.2
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none" ## Vectorization handled externally
      CLUSTER_HOSTNAME: "node1"

  embedding_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding_api
    ports:
      - "8000:8000"
    environment:
      EMBEDDING_MODEL: BAAI/bge-small-en
      MODEL_CACHE_DIR: /models_cache
      HF_HOME: /models_cache
      NORMALIZE_EMBEDDINGS: "true"
    volumes:
      - ./hf_cache:/models_cache
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  weaviate_data:
